#!/bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        2
bspc config window_gap          1
bspc config normal_border_color "#ffffff"
bspc config focused_border_color "#9999ff" 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_mouse true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd &
polybar &
setxkbmap -option grp:alt_shift_toggle us,ru &
xinput set-prop "$(xinput list | grep -i 'touchpad' | grep -o 'id=[0-9]*' | cut -d= -f2)" "libinput Tapping Enabled" 1

~/.config/scripts/change_wallpapers.sh
